### PR TITLE
FIrst pull request from Feature branch to Master brach

### PR DESCRIPTION
**Pull request by andresporras3423**
important features: 

* Using bootstrap
* customized bootstrap using https://bootstrap.build/ the only feature that I customized was the numbers of columns, by default is 12, I changed it for 60 (thanks to this change I was able to make a complete responsive page layout only using bootstrap classes) 
* Besides the layout classes, I had used other bootstrap classes like d-flex, text-center, justify-content-end, text-white, row, navbar, and some others.
* I had also used fontawesome to the icons of social networks and menu
* I added Roboto font, from google fonts, to make the font more similar to the original page

### CODE REVIEW

**Comment by pelzolga123** [comment]
### Hi Oscar! I am marking this review request as invalid, because your linter is not setup for this repository. 
Please kindly setup linter and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Comment by andresporras3423** [comment]
Hi Olga,
Thanks, I will do that

**Comment by andresporras3423** [comment]
Linter setup and all checks have passed

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes 🔴 

Hi @andresporras3423, 🙂  you did a great work setting up linter for this repo 👍 . However, there are comments we need to address.  Find comment below:
- Kindly fix the error returned by [css validator](https://jigsaw.w3.org/css-validator)
fy
- ```Mobile mode``` there is a horizontal scroll
ms
- Let us fix ```Opinion``` section on ```tablet mode```. Currently,  it looks like this
cop
It should be this
nop
- Currently, the latest news looks like this
lato
Instead of 
latn

Kindly make these changes and submit code review 😄 
Happy coding 💻 
Daniel Larbi Addo

**Comment by andresporras3423** [comment]
I have made the suggested corrections:
- overflow of the x axis
- corrections in latest news and opinion sections
- corrected problems in css validator

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes 🔴 

Hi @andresporras3423, you did a great job making the changes. However, we still have horizontal scroll on both ```mobile```
stc
and 
stc1
```tablet```


Kindly fix this and submit another code review 👍 
Happy coding 💻

**Comment by andresporras3423** [comment]
oh sorry, you are right. I will make the change

**Comment by andresporras3423** [comment]
x overflow just for mobile screens

**Review by rOluochKe — APPROVED** [review]
Hello Team!
### You have done a good job. I, therefore, approve of your project. Congratulations :clap: :boom:
### You can merge and submit a project completion form from your dashboard.
- Happy coding!

**Comment by andresporras3423** [comment]
thanks

**Pull request merged**
